[paths]
win_path_jp = "~\\AppData\\LocalLow\\Cygames\\umamusume"
win_path_ko = "~\\AppData\\LocalLow\\umamusume_ko"
win_path_tw = "~\\AppData\\LocalLow\\umamusume_tw"
master_db = "master\\master.mdb"
backup_file = "master\\master.mdb.bak"
working_backup_file = "master\\master.mdb.bak.working"

[relevant_tables]
query = """
SELECT tbl_name FROM sqlite_master
WHERE type='table' and tbl_name not like 'sqlite_%' and (tbl_name LIKE '%data%' OR tbl_name LIKE '%set%');
"""

[character_data]
main_table = "card_rarity_data"
relation_tables = ["text_data", "skill_set", "card_data"]
query = """
SELECT
	td_names.text AS name,
	td_costume_en.text AS dress_name_en,
	td_costume_jp.text AS dress_name_jp,
	td_skills.text AS unique_skill_name,
	cd.rarity AS star_level,
	cd.speed,
	cd.stamina,
	cd.pow AS power,
	cd.guts,
	cd.wiz AS wisdom,
	cd.max_speed,
	cd.max_stamina,
	cd.max_pow AS max_power,
	cd.max_guts,
	cd.max_wiz AS max_wisdom,
	card.limited_chara AS is_limited_char,
	printf("%.2f%%", card.talent_speed) AS speed_pct_increase,
	printf("%.2f%%", card.talent_stamina) AS stamina_pct_increase,
	printf("%.2f%%", card.talent_pow) AS power_pct_increase,
	printf("%.2f%%", card.talent_guts) AS guts_pct_increase,
	printf("%.2f%%", card.talent_wiz) AS wisdom_pct_increase,
	CASE WHEN cd.proper_distance_short = 1
			THEN "G"
		WHEN cd.proper_distance_short = 2
			THEN "F"
		WHEN cd.proper_distance_short = 3
			THEN "E"
		WHEN cd.proper_distance_short = 4
			THEN "D"
		WHEN cd.proper_distance_short = 5
			THEN "C"
		WHEN cd.proper_distance_short = 6
			THEN "B"
		WHEN cd.proper_distance_short = 7
			THEN "A"
		WHEN cd.proper_distance_short = 8
			THEN "S"
		ELSE "Unknown"
			END AS distance_short_rating,
	CASE WHEN cd.proper_distance_mile = 1
			THEN "G"
		WHEN cd.proper_distance_mile = 2
			THEN "F"
		WHEN cd.proper_distance_mile = 3
			THEN "E"
		WHEN cd.proper_distance_mile = 4
			THEN "D"
		WHEN cd.proper_distance_mile = 5
			THEN "C"
		WHEN cd.proper_distance_mile = 6
			THEN "B"
		WHEN cd.proper_distance_mile = 7
			THEN "A"
		WHEN cd.proper_distance_mile = 8
			THEN "S"
		ELSE "Unknown"
			END AS distance_mile_rating,
	CASE WHEN cd.proper_distance_middle = 1
			THEN "G"
		WHEN cd.proper_distance_middle = 2
			THEN "F"
		WHEN cd.proper_distance_middle = 3
			THEN "E"
		WHEN cd.proper_distance_middle = 4
			THEN "D"
		WHEN cd.proper_distance_middle = 5
			THEN "C"
		WHEN cd.proper_distance_middle = 6
			THEN "B"
		WHEN cd.proper_distance_middle = 7
			THEN "A"
		WHEN cd.proper_distance_middle = 8
			THEN "S"
		ELSE "Unknown"
			END AS distance_rating_middle,
	CASE WHEN cd.proper_distance_long = 1
			THEN "G"
		WHEN cd.proper_distance_long = 2
			THEN "F"
		WHEN cd.proper_distance_long = 3
			THEN "E"
		WHEN cd.proper_distance_long = 4
			THEN "D"
		WHEN cd.proper_distance_long = 5
			THEN "C"
		WHEN cd.proper_distance_long = 6
			THEN "B"
		WHEN cd.proper_distance_long = 7
			THEN "A"
		WHEN cd.proper_distance_long = 8
			THEN "S"
		ELSE "Unknown"
			END AS distance_long_rating,
	CASE WHEN cd.proper_running_style_nige = 1
			THEN "G"
		WHEN cd.proper_running_style_nige = 2
			THEN "F"
		WHEN cd.proper_running_style_nige = 3
			THEN "E"
		WHEN cd.proper_running_style_nige = 4
			THEN "D"
		WHEN cd.proper_running_style_nige = 5
			THEN "C"
		WHEN cd.proper_running_style_nige = 6
			THEN "B"
		WHEN cd.proper_running_style_nige = 7
			THEN "A"
		WHEN cd.proper_running_style_nige = 8
			THEN "S"
		ELSE "Unknown"
			END AS runner_rating,
	CASE WHEN cd.proper_running_style_senko = 1
			THEN "G"
		WHEN cd.proper_running_style_senko = 2
			THEN "F"
		WHEN cd.proper_running_style_senko = 3
			THEN "E"
		WHEN cd.proper_running_style_senko = 4
			THEN "D"
		WHEN cd.proper_running_style_senko = 5
			THEN "C"
		WHEN cd.proper_running_style_senko = 6
			THEN "B"
		WHEN cd.proper_running_style_senko = 7
			THEN "A"
		WHEN cd.proper_running_style_senko = 8
			THEN "S"
		ELSE "Unknown"
			END AS leader_rating,
	CASE WHEN cd.proper_running_style_sashi = 1
			THEN "G"
		WHEN cd.proper_running_style_sashi = 2
			THEN "F"
		WHEN cd.proper_running_style_sashi = 3
			THEN "E"
		WHEN cd.proper_running_style_sashi = 4
			THEN "D"
		WHEN cd.proper_running_style_sashi = 5
			THEN "C"
		WHEN cd.proper_running_style_sashi = 6
			THEN "B"
		WHEN cd.proper_running_style_sashi = 7
			THEN "A"
		WHEN cd.proper_running_style_sashi = 8
			THEN "S"
		ELSE "Unknown"
			END AS betweener_rating,
	CASE WHEN cd.proper_running_style_oikomi = 1
			THEN "G"
		WHEN cd.proper_running_style_oikomi = 2
			THEN "F"
		WHEN cd.proper_running_style_oikomi = 3
			THEN "E"
		WHEN cd.proper_running_style_oikomi = 4
			THEN "D"
		WHEN cd.proper_running_style_oikomi = 5
			THEN "C"
		WHEN cd.proper_running_style_oikomi = 6
			THEN "B"
		WHEN cd.proper_running_style_oikomi = 7
			THEN "A"
		WHEN cd.proper_running_style_oikomi = 8
			THEN "S"
		ELSE "Unknown"
			END AS chaser_rating,
	CASE WHEN cd.proper_ground_turf = 1
			THEN "G"
		WHEN cd.proper_ground_turf = 2
			THEN "F"
		WHEN cd.proper_ground_turf = 3
			THEN "E"
		WHEN cd.proper_ground_turf = 4
			THEN "D"
		WHEN cd.proper_ground_turf = 5
			THEN "C"
		WHEN cd.proper_ground_turf = 6
			THEN "B"
		WHEN cd.proper_ground_turf = 7
			THEN "A"
		WHEN cd.proper_ground_turf = 8
			THEN "S"
		ELSE "Unknown"
			END AS turf_rating,
	CASE WHEN cd.proper_ground_dirt = 1
			THEN "G"
		WHEN cd.proper_ground_dirt = 2
			THEN "F"
		WHEN cd.proper_ground_dirt = 3
			THEN "E"
		WHEN cd.proper_ground_dirt = 4
			THEN "D"
		WHEN cd.proper_ground_dirt = 5
			THEN "C"
		WHEN cd.proper_ground_dirt = 6
			THEN "B"
		WHEN cd.proper_ground_dirt = 7
			THEN "A"
		WHEN cd.proper_ground_dirt = 8
			THEN "S"
		ELSE "Unknown"
			END AS dirt_rating
FROM card_rarity_data cd
	LEFT JOIN text_data td_names
		ON SUBSTR(cd.card_id, 1, 4) = td_names.`index`
		AND td_names.id = 6
		AND td_names.category = 6
	LEFT JOIN text_data td_costume_en
		ON cd.card_id = td_costume_en.`index`
		AND td_costume_en.id = 5
		AND td_costume_en.category = 5
	LEFT JOIN text_data td_costume_jp
		ON cd.get_dress_id_2 = td_costume_jp.`index`
		AND td_costume_jp.id = 14
		AND td_costume_jp.category = 14
	LEFT JOIN skill_set sk
		ON cd.skill_set = sk.id
	LEFT JOIN text_data td_skills
		ON sk.skill_id1 = td_skills.`index`
		AND td_skills.id = 47
		AND td_skills.category = 47
	LEFT JOIN card_data card
		ON cd.card_id = card.id
"""
note = "To fetch the document for the main character data."


[[table_relation_ids]]
base_table = "text_data"
search_column = "category"
index_column = "index"

[[table_relation_ids.uma_titles]]
category = 5
note = "To fetch the document for the character's dress name."

[[table_relation_ids.uma_names]]
category = [
	6,77,78,170,182
]
note = "To fetch the document for the character's name."

[[table_relation_ids.item_names]]
category = 23
note = "To fetch the document for the item name."

[[table_relation_ids.item_description]]
category = 24
note = "To fetch the document for the item description."

[[table_relation_ids.item_groups]]
category = 133
note = "To fetch the document for the item group name."

[[table_relation_ids.skill_names]]
category = 47
special_query = "(category = 147 AND \"index\" BETWEEN 2000100 AND 3000100)"
note = "To fetch the document for the skill name."

[[table_relation_ids.skill_descriptions]]
category = 48
note = "To fetch the document for the skill description."

[[table_relation_ids.race_names]]
special_query = "(category IN (28,29,32,33,36,111,218) AND \"index\" BETWEEN 20000 AND 30000)"
note = "To fetch the document for the names of all of the races."

[[table_relation_ids.race_tracks]]
category = [31,35]
