[paths]
win_path = "~\\AppData\\LocalLow\\Cygames\\umamusume"
master_db = "master\\master.mdb"
meta_db = "meta"
backup_file = "master\\master.mdb.bak"
working_backup_file = "master\\master.mdb.bak.working"
asset_path = "dat"

[meta_tables]
blob_table = 'a'
blob_table_PATH = 'n'
blob_table_HASH = 'h'
blob_table_KIND = 'm'
