[paths]
win_path_jp = "~\\AppData\\LocalLow\\Cygames\\umamusume"
win_path_ko = "~\\AppData\\LocalLow\\umamusume_ko"
win_path_tw = "~\\AppData\\LocalLow\\umamusume_tw"
meta_db = "meta"
asset_path = "dat"

[meta_tables]
blob_table = 'a'
blob_table_PATH = 'n'
blob_table_HASH = 'h'
blob_table_KIND = 'm'
